spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        password: nacos
        username: nacos
  main:
    allow-bean-definition-overriding: true


#暴露监控
management:
  endpoints:
    web:
      exposure:
        include: "*"

# feign调用超时时间配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000